[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
chrono = { version = "0.4.41", features = ["serde"] }
dotenvy = "0.15.7"
mongodb = "3.2.4"
serde = "1.0.219"
serde_json = "1.0.142"
tokio = "1.47.1"
tokio-stream = "0.1.17"
